add condition in the github action

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -18,4 +18,8 @@ jobs:
         run: |
           cd client
           npm run build 
+          if [ $? -ne 0 ]; then
+            echo "Error: Application build failed!"
+            exit 1
+          fi
           echo "Application build successfully!"
